### ISSUE TITLE
Project Grid CF 

### ISSUE THREAD

**Issue by winnie151** [CodetheChangeFoundation/patientsineducation#10]
Acceptance criteria: 
Rule 1: When not click on either projects, the projects are aligned in shape with 3 columns and rows(depend on project count).
Rule 2: Project elements are oriented as full image on top followed by project name and description.
Rule 3: When user click on one project's short description, a speech balloon will show up beneath the project, and the following row moves down. 
Rule 4: 'Learn more' button inside the speech balloon
Rule 5: Adjusted with the page size
Rule 6: Archive
Out of scope:

**Comment by AliciaYang** [comment]
Project Grid custom field is working, moving on to project description box
