### ISSUE TITLE
About page more about PIE section

### ISSUE THREAD

**Issue by Dara2004** [CodetheChangeFoundation/patientsineducation#22]
### Acceptance Criteria:
* 4 sections each with an image, a title, and a paragraph
* Text section should have a rounded border similar to the one on the homepage
* Images stack on top of text sections on mobile

### Definition of Done:
* Wiki updated

**Comment by AliciaYang** [comment]
Branch PIE-22:
Created "more-about-pie" custom field;
Styled the custom field;
Some viewpoint errors remain to be fixed
