### ISSUE TITLE
Navbar has a larger height than it should

### ISSUE THREAD

**Issue by mrdollarbill** [CodetheChangeFoundation/patientsineducation#51]
![screenshot 1](https://user-images.githubusercontent.com/43835802/51592573-d2b41d80-1ea4-11e9-8fd4-a6fc6717960c.png)

Navbar takes up more space than it should and overlaps the page title (seen in Google Chrome and Firefox)

**Comment by pritpalc** [comment]
Can you double check this again with the most up to date master branch?

**Comment by mrdollarbill** [comment]
Looks good now
