### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by pritpalc** [CodetheChangeFoundation/patientsineducation#60]
### Acceptance Criteria:
* Add appropriate alt tags to all images in WP
* Make sure correct HTML tags are used
* ARIA labelling
* Double check sizing on different devices and browsers

### Approach:
* Test using https://wave.webaim.org/
* For keyboard accessibility tips https://webdesign.tutsplus.com/articles/keyboard-accessibility-tips-using-html-and-css--cms-31966
* https://www.w3.org/WAI/fundamentals/accessibility-intro/

**Comment by vinielk** [comment]
### Accessibility changes made (so far)
* replaced background-image with img + alt tags
  * fallback for IE (and other browsers that don't support _'object-fit'_ css property) still uses background-image

**Comment by vinielk** [comment]
Took about 7-8 hours. Needed to do research about best accessibility practices and also had to do a lot of testing.
