### ISSUE TITLE
Mobile contact us tabs restyling

### ISSUE THREAD

**Issue by pritpalc** [CodetheChangeFoundation/patientsineducation#77]
### Acceptance Criteria:
* Restyle contact us tabs on mobile to look like buttons or some sort of menu

![IMG_0816](https://user-images.githubusercontent.com/30644663/55907713-5b7d5400-5b8c-11e9-9f8f-ee7322983ded.jpeg)

##### Tested on iPhone 8 Safari

**Comment by vinielk** [comment]
Took about 2-3 hours. Spend a lot of time experimenting with different options and testing.
