### ISSUE TITLE
Mobile members page svg

### ISSUE THREAD

**Issue by pritpalc** [CodetheChangeFoundation/patientsineducation#78]
### Acceptance Criteria:
* Fix SVG on members page so that there's no overflow and it's less stretched

![IMG_0817](https://user-images.githubusercontent.com/30644663/55907771-85367b00-5b8c-11e9-81d1-3403b1fbd241.jpeg)

##### Tested on iPhone 8 Safari

**Comment by vinielk** [comment]
Took 1-2 hours. Spent time finding best solution and testing.
