### ISSUE TITLE
Outreach archive button and fonts (Surface)

### ISSUE THREAD

**Issue by pritpalc** [CodetheChangeFoundation/patientsineducation#79]
### Acceptance Criteria:
* Archive button should work on a Microsoft Surface (both touch and by mouse)
* Fonts are displaying as Times New Roman on Surface

**Comment by vinielk** [comment]
Took 1 hour. Hard to debug because I don't have a windows device...

**Comment by vinielk** [comment]
Took additional 1 hour to test and debug. Used browserling to test on IE11. Updated wiki to include browser support for website.
