### ISSUE TITLE
Fix 'Members' format

### ISSUE THREAD

**Issue by pritpalc** [CodetheChangeFoundation/patientsineducation#81]
### Acceptance Criteria:
* On the about us page, the word "Members" breaks onto a new line on smaller screens
* Break earlier

<img width="715" alt="Screen Shot 2019-05-08 at 9 25 34 PM" src="https://user-images.githubusercontent.com/30644663/57430086-60611200-71e3-11e9-84da-47d4a5335488.png">

**Comment by vinielk** [comment]
Took 1 hour
